version: '2.6'
services:
  STUI:
    container_name: STUI
    image: nginx
    restart: always
    ports:
      - 8889:8080
    volumes:
      - ./dist:/webserver
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-log:/var/log/nginx
